### PR TITLE
adds capacity for jruby-jars gem for jruby-9k (second try)

### PR DESCRIPTION
**Pull request by rebelwarrior**
Hi,
I changed the gemspec requirements so warbler would work with jruby-9k jars including the preview release. It uses a regular expression to see if you are using jruby-9k and then uses that version as the gemspec for jruby-jars. It's a little hacky but it works. One must then use bundle exec warble to test.

Produces this warning: 
file:/Users/name/.rvm/rubies/jruby-9.0.0.0.pre1/lib/jruby.jar!/jruby/kernel/kernel.rb:28: warning: unsupported exec option: close_others
but works anyway.

##New: Added a defined? check on JRUBY_VERSION constant before checking to prevent Travis CI error when variables not set. 

Thanks,

David Acevedo

### CODE REVIEW

**Comment by jkutner** [comment]
I'm thinking about starting a 2.0 branch, merging this into it, and then releasing some 2.0.0.pre releases. I'm not sure if I want to support 9k in 1.4.x at all if possible. I'll have this merged (one way or another) soon.

**Comment by MSNexploder** [comment]
+1 for keeping 1.4.x on JRuby 1.7.x only and starting a 2.0 branch for 9k upwards.

**Comment by jkutner** [comment]
Merged in 2.x-dev branch

**Comment by jkutner** [comment]
Not sure why i left this open. I think i got the changes moved in correctly. please let me know if i'm wrong.

**Pull request closed without merging**
