### PR TITLE
Update default maven url

### LINKED ISSUE #463: Broken default maven repo url causes mysterious errors
Building with the default maven url defined at https://github.com/jruby/warbler/blob/82c15c57119f7a3ccde69495522ffcddb7e202eb/lib/warbler/web_server.rb#L91 results in this: 

```
09:08:05 + exec bundle _1.17.3_ exec warble runnable executable war
09:08:31 Downloading jetty-runner-9.4.12.v20180830.jar
09:08:31 warble aborted!
09:08:31 can't modify frozen String
09:08:31 /home/jenkins/.rvm/gems/jruby-9.1.17.0@l4e/gems/warbler-2.0.4/lib/warbler/web_server.rb:31:in `local_path'
09:08:31 /home/jenkins/.rvm/gems/jruby-9.1.17.0@l4e/gems/warbler-2.0.4/lib/warbler/web_server.rb:81:in `add'
09:08:31 /home/jenkins/.rvm/gems/jruby-9.1.17.0@l4e/gems/warbler-2.0.4/lib/warbler/web_server.rb:97:in `add'
09:08:31 /home/jenkins/.rvm/gems/jruby-9.1.17.0@l4e/gems/warbler-2.0.4/lib/warbler/traits/war.rb:116:in `add_executables'
09:08:31 /home/jenkins/.rvm/gems/jruby-9.1.17.0@l4e/gems/warbler-2.0.4/lib/warbler/traits/war.rb:81:in `update_archive'
```

The frozen string error is because a RuntimeError is raised to here: https://github.com/jruby/warbler/blob/82c15c57119f7a3ccde69495522ffcddb7e202eb/lib/warbler/web_server.rb#L31 That handling should probably be improved to not assume message can be modified.

Removing that line locally you can get
```
Downloading jetty-runner-9.2.9.v20150224.jar
warble aborted!
redirection forbidden: http://repo2.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.2.9.v20150224/jetty-runner-9.2.9.v20150224.jar -> https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.2.9.v20150224/jetty-runner-9.2.9.v20150224.jar
```

Using `MAVEN_REPO=https://repo1.maven.org/maven2 bundle exec warble runnable executable war` instead works.

### PR DESCRIPTION
**Pull request by keegangroth**
Fixes #463

### CODE REVIEW

**Comment by keegangroth** [comment]
oh I wasn't expect to get that merged so quickly, thanks! I'm not sure this has really improved the travis situation though haha

**Comment by headius** [comment]
@keegangroth Oh shoot yeah...it looked ok to me but seems to be regressing more builds than it's helping. I'm going to revert and we'll try again.

**Comment by headius** [comment]
Looks like your changes actually passed more jobs than without, so I've left them in place. Not sure what's up with that bundler version mismatch yet.

**Comment by keegangroth** [comment]
as far as I can tell, travis (or rvm or ruby) is just being difficult about uninstalling bundler 2.x and jbundler wants a 1.x (I think the jdk change is good though)

**Comment by headius** [comment]
I think we need a jbundler release that's up to date with bundler proper, right @mkristian?

**Comment by mkristian** [comment]
@headius yes, this jbundler with bundler2 is in my todo for this weekend

**Comment by headius** [comment]
@mkristian What's the status of the updated jbundler?

**Comment by mkristian** [comment]
@headius updated jbundler but got stuck in 'fixing' 3 failing integration tests. one I ran into all kind of problems even NPE inside JRuby

**Comment by headius** [comment]
Oh, lovely 😜

Do let me know if there's anything I can help with!

**Pull request merged**
