### PR TITLE
update Jetty to 9.2.10

### PR DESCRIPTION
**Pull request by MSNexploder**
Did some smoke testing using a simple Rails App - everything works just fine.
My maven-foo is rather limited, so hopefully i didn't mess anything up.

### CODE REVIEW

**Comment by mkristian** [comment]
@MSNexploder  the maven bits look OK ;)

**Comment by MSNexploder** [comment]
@mkristian \o/ \o/

**Comment by kares** [comment]
Excellent Stefan!

... on a related note I was hoping we won't need releases of that jetty wrapping pom to keep it updated ;(

**Comment by jkutner** [comment]
Thanks!

**Pull request merged**
