### PR TITLE
fix classloader setup for WarMain

### PR DESCRIPTION
**Pull request by mkristian**
and see if newer versions of the maven stuff works.

### CODE REVIEW

**Comment by jkutner** [comment]
taking a look now

**Comment by mkristian** [comment]
still waiting for some feedback of my colleague whether this really fixes all the issues with jruby-9k he has with his project. I just fixed the obvious so far.

**Comment by mkristian** [comment]
@jkutner on our side things start to work again with this fix. would do you think ? merge and maybe even a release 2.0.0.rc2 ?

**Comment by jkutner** [comment]
Yea, i tested it out with my projects and it worked fine. I'll merge and cut a release

**Comment by ismith** [comment]
Works for me as well (I'm the colleage @mkristian mentioned).

**Pull request merged**
