### PR TITLE
[Gems] Match Gem::BasicSpecification

### PR DESCRIPTION
**Pull request by segiddins**
Hopefully closes https://github.com/bundler/bundler/issues/3691.

### CODE REVIEW

**Comment by segiddins** [comment]
I don't know what this gem does, so I was just trying to help out and share a potential fix due to changes in bundler's private internals.

**Comment by kares** [comment]
@segiddins we very much appreciate your patch ... and you do not need to know much, just advised that if you've kept the `Gem::Specification` as before (`BasicSpecification` might be checked as well but only if it's available) it would have been merge ready material :)

**Comment by abiacco** [comment]
So i used 1.4.8 to fix the referenced bundler error, BUT, i needed to use jruby-jars 1.7.20.1 to install it. Problem is i'm testing jruby 9000rc1, so think i need to use jruby-jars 9.0.0.0.rc1.
Any chance this can be ported to the 2.x branch so i can move forward with it?
Thanks.

**Comment by jkutner** [comment]
@abiacco yup. mind putting it in a PR against the 2.x-dev branch?

**Comment by abiacco** [comment]
@jkutner hmm, i can, but the current patch against 2.x-dev doesn't fix the error. the gem built and installed fine, but got the same error in my app build, so i assume something else needs to be done.

**Pull request closed without merging**
