### PR TITLE
Update the History.txt since v2.0.5

### PR DESCRIPTION
**Pull request by nbekirov**
This PR aims at completing the "v2.0.5...master look through, and find items for History.txt" task from #498

### CODE REVIEW

**Comment by nbekirov** [comment]
Anyone out there?

**Comment by olleolleolle** [comment]
Hello! Thanks for the update - the other History.txt lines are edited a bit, to omit commits that do not really communicate much that the reader needs to act on.

Compare the other releases.

To merge this, History.txt should have a short list of user-facing, important changes. 

Hope this helps!

**Comment by nbekirov** [comment]
Thank you, @olleolleolle! I'll look int this :)

**Comment by olleolleolle** [comment]
@nbekirov I made an attempt, and merged it, thanks for starting this!

**Pull request merged**
