### PR TITLE
Added Gem.reload_paths to fix issue with deploying with 9.2.x

### PR DESCRIPTION
**Pull request by rsov**
This is a quick fix for https://github.com/jruby/warbler/issues/432 and https://github.com/jruby/warbler/issues/430

### CODE REVIEW

**Comment by mengu** [comment]
hi @rsov 

if i may, where does the refresh_paths method come from?

**Comment by rsov** [comment]
@mengu Sorry, I meant `clear_paths`. And it comes from rubygems: https://www.rubydoc.info/stdlib/rubygems/Gem.clear_paths

**Comment by kares** [comment]
very nice, [method has existed](https://github.com/rubygems/rubygems/blob/2.7/lib/rubygems.rb#L337-L342) way long (at least since RGs 2.0) ... makes sense to reset.

**Comment by mengu** [comment]
@rsov, and i meant reload_paths :-)

if reload_path is not an alias for clear_paths, reload_paths does not exist in the Gem module hence the merged PR will raise an exception.

**Comment by kares** [comment]
oh right, `clear_paths` is mentioned so I checked that one - seems there isn't such method at RubyGems.
could we maybe not shoot for such breaking (non-mergable) PRs next time please?
if you'd like to show up in a comment that you have smt in mind you could just point them to a commit ...

**Comment by mengu** [comment]
well, i didn't know we could jump in for a code review. next time i'll surely do that.

**Comment by rsov** [comment]
Indeed. I have made a mistake. I could push up the fixed code or if you like, can troubleshoot to see if it can be fixed somewhere upstream. Unless there's a fix coming in the next version of jruby

**Pull request merged**
