### PR TITLE
Added Gem.clear_paths to bundler.erb

### PR DESCRIPTION
**Pull request by rsov**
Tried deploying with Bundler 1.16.3 and it did not seem to resolve the issues with https://github.com/jruby/warbler/issues/432

Submitting the fix again (with proper method call this time)

### CODE REVIEW

**Comment by rsov** [comment]
Should fix https://github.com/jruby/warbler/issues/432, https://github.com/jruby/warbler/issues/430 and https://github.com/jruby/warbler/issues/415

**Comment by timbogit** [comment]
@rsov / @ kares : any chance this fix can be merged soon?
Using the branch for this PR locally in our (JRuby 9.2.0.0) project appears to resolve the issue.
I see that the Travis build is broken for one version, though. Maybe that can be addressed?
Or is the preferred solution to wait for a change in bundler to be released (as mentioned in #432 ) and then hope that fixes 9.2.0.0 support?

**Comment by rsov** [comment]
@timbogit I have tried it with updated version of bundler and it did not fix the issue

**Comment by kares** [comment]
as noted previously, this isnt a good work-around https://github.com/jruby/warbler/issues/432#issuecomment-404799363 ... likely a JRuby 9.2 bug

**Comment by mungler** [comment]
Bug appears to be still present in JRuby 9.2.1.0 :/

**Pull request closed without merging**
